#!/usr/bin/env python3
"""Analysis 7 -- Representation Similarity (CKA) plots.

Loads pre-computed CKA data from data/maskfix_data.npz and generates:
  plots/cka_by_layer.png  -- Bar chart of linear CKA per layer (3 pairs)
  plots/cka_heatmap.png   -- Cross-layer CKA heatmap (M1 vs M3)

Data generated by:
    PYTHONPATH=. .venv/bin/python analysis/report_7/scripts/generate_data.py

Runnable without a GPU:
    PYTHONPATH=. .venv/bin/python analysis/report_7/scripts/generate_plots.py
"""
from __future__ import annotations

import os
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
REPORT_DIR = SCRIPT_DIR.parent
DATA_FILE = REPORT_DIR / "data" / "maskfix_data.npz"
OUT_DIR = REPORT_DIR / "plots"

NUM_LAYERS = 16
LAYER_LABELS = ["emb"] + [f"L{i}" for i in range(NUM_LAYERS)]

M1_M3_COLOR = "#1f77b4"
M1_M2_COLOR = "#ff7f0e"
M2_M3_COLOR = "#2ca02c"


def plot_cka_by_layer(data: dict[str, np.ndarray], out_dir: Path) -> None:
    """Bar chart of linear CKA at each layer for all available pairs."""
    cka_m1_m3 = data["layer_cka_maskfix"]
    has_m2 = "layer_cka_m1_m2" in data
    n = len(cka_m1_m3)
    labels = LAYER_LABELS[:n]
    x = np.arange(n)

    if has_m2:
        cka_m1_m2 = data["layer_cka_m1_m2"]
        cka_m2_m3 = data["layer_cka_m2_m3"]
        width = 0.25
        fig, ax = plt.subplots(figsize=(14, 6))
        ax.bar(x - width, cka_m1_m2, width, label="M1 vs M2 (M1 LoRA effect)",
               color=M1_M2_COLOR, alpha=0.85)
        ax.bar(x, cka_m2_m3, width, label="M2 vs M3 (M3 LoRA effect)",
               color=M2_M3_COLOR, alpha=0.85)
        ax.bar(x + width, cka_m1_m3, width, label="M1 vs M3 (between LoRAs)",
               color=M1_M3_COLOR, alpha=0.85)
    else:
        width = 0.5
        fig, ax = plt.subplots(figsize=(12, 5))
        ax.bar(x, cka_m1_m3, width, label="M1 vs M3", color=M1_M3_COLOR,
               alpha=0.85)

    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=9)
    ax.set_xlabel("Layer", fontsize=12)
    ax.set_ylabel("Linear CKA", fontsize=12)
    ax.set_title("Representation Similarity (CKA) per Layer",
                 fontsize=13, fontweight="bold")

    # Set y-axis to show detail near 1.0
    all_vals = [cka_m1_m3]
    if has_m2:
        all_vals.extend([cka_m1_m2, cka_m2_m3])
    ymin = min(v.min() for v in all_vals) - 0.005
    ax.set_ylim(max(0, ymin), 1.005)
    ax.axhline(y=1.0, color="grey", linestyle=":", alpha=0.4)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3, axis="y")

    fig.tight_layout()
    path = out_dir / "cka_by_layer.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"Saved {path}")


def plot_cka_heatmap(cross_cka: np.ndarray, title_a: str, title_b: str,
                     filename: str, out_dir: Path) -> None:
    """Cross-layer CKA heatmap."""
    n = cross_cka.shape[0]
    labels = LAYER_LABELS[:n]

    fig, ax = plt.subplots(figsize=(10, 9))
    im = ax.imshow(cross_cka, cmap="viridis", vmin=0, vmax=1,
                   aspect="equal", origin="lower")
    ax.set_xticks(range(n))
    ax.set_xticklabels(labels, fontsize=8, rotation=45, ha="right")
    ax.set_yticks(range(n))
    ax.set_yticklabels(labels, fontsize=8)
    ax.set_xlabel(f"{title_b} Layer", fontsize=12)
    ax.set_ylabel(f"{title_a} Layer", fontsize=12)
    ax.set_title(f"Cross-Layer CKA: {title_a} vs {title_b}\n"
                 "Off-diagonal peaks suggest computational shifts",
                 fontsize=13)

    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("Linear CKA", fontsize=11)

    if n <= 17:
        for i in range(n):
            for j in range(n):
                val = cross_cka[i, j]
                text_color = "white" if val < 0.5 else "black"
                ax.text(j, i, f"{val:.2f}", ha="center", va="center",
                        fontsize=6, color=text_color)

    ax.plot([-0.5, n - 0.5], [-0.5, n - 0.5], "r--", linewidth=1, alpha=0.5)
    fig.tight_layout()
    path = out_dir / filename
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"Saved {path}")


def print_summary(data: dict[str, np.ndarray]) -> None:
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    pairs = [
        ("M1 vs M3", "layer_cka_maskfix"),
    ]
    if "layer_cka_m1_m2" in data:
        pairs.append(("M1 vs M2", "layer_cka_m1_m2"))
        pairs.append(("M2 vs M3", "layer_cka_m2_m3"))

    for label, key in pairs:
        cka = data[key]
        min_idx = int(np.argmin(cka))
        min_label = "emb" if min_idx == 0 else f"L{min_idx - 1}"
        print(f"\n{label}:")
        print(f"  mean={cka.mean():.4f}  min={cka.min():.4f} ({min_label})  "
              f"max={cka.max():.4f}")


def main() -> None:
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Data file not found: {DATA_FILE}\n"
            "Generate it with:\n"
            "  PYTHONPATH=. .venv/bin/python analysis/report_7/scripts/generate_data.py"
        )

    data = dict(np.load(DATA_FILE))
    print(f"Loaded {DATA_FILE}")
    print(f"  Keys: {sorted(data.keys())}")

    os.makedirs(OUT_DIR, exist_ok=True)

    plot_cka_by_layer(data, OUT_DIR)
    plot_cka_heatmap(data["cross_cka_maskfix"], "M1", "M3",
                     "cka_heatmap.png", OUT_DIR)

    print_summary(data)
    print("\nDone.")


if __name__ == "__main__":
    main()
