# =============================================================================
# evo-memory — Unified Makefile
#
# Replaces the setup/*.sh scripts with declarative, DRY targets.
#
# Quick start:
#   make setup-local          # CPU / local GPU (auto CUDA if nvidia-smi found)
#   make setup-gpu GPU=2      # pin to a specific GPU index
#   make setup-tpu            # Google Cloud TPU VM
#   make setup-ucl-gpu        # UCL CSH cluster (GPU, no GCS/wandb)
#
# Activate in subsequent shells:
#   source activate.sh        # bash / zsh
#   source activate.csh       # csh / tcsh (UCL machines)
#
# See: make help
# =============================================================================

SHELL       := /bin/bash
.DEFAULT_GOAL := help

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO_DIR    := $(CURDIR)
VENV_DIR    := $(REPO_DIR)/venv
PYTHON      := $(VENV_DIR)/bin/python
PIP         := $(VENV_DIR)/bin/pip
STAMPS      := $(REPO_DIR)/.make

# ── Tunables (override on the command line) ───────────────────────────────────
GPU         ?=
GCS_BUCKET  ?= statistical-nlp
GCS_PROJECT ?= statistical-nlp
HF_CACHE_DIR?= $(REPO_DIR)/.hf_cache
XLA_CACHE   := $(REPO_DIR)/.xla_cache

# ── Requirement files ─────────────────────────────────────────────────────────
REQUIREMENTS := $(REPO_DIR)/requirements.txt

# Filter: everything except torch/torchvision/torchaudio and index-url lines
define FILTER_NON_TORCH
grep -vE '^(torch|torchvision|torchaudio|--index-url|--extra-index-url|[[:space:]]*\#|[[:space:]]*$$)' $(REQUIREMENTS)
endef

# =============================================================================
#  Internal plumbing (stamp files avoid redundant work)
# =============================================================================
$(STAMPS):
	@mkdir -p $@

# ── Virtual-environment creation ──────────────────────────────────────────────
$(STAMPS)/venv: | $(STAMPS)
	@echo "Creating virtualenv at $(VENV_DIR) ..."
	python3 -m venv $(VENV_DIR)
	$(PIP) install --upgrade pip setuptools -q
	@touch $@

# ── Base Python deps (everything except PyTorch) ─────────────────────────────
$(STAMPS)/base: $(STAMPS)/venv $(REQUIREMENTS) | $(STAMPS)
	@echo "Installing shared Python dependencies ..."
	$(FILTER_NON_TORCH) | $(PIP) install -q -r /dev/stdin
	@touch $@

# ── activate.sh generation ───────────────────────────────────────────────────
# Thin, generated script — the Makefile is the single source of truth.
$(REPO_DIR)/activate.sh: $(STAMPS)/venv
	@echo "Generating activate.sh ..."
	@{ \
	echo '#!/usr/bin/env bash'; \
	echo '# Auto-generated by Makefile — do not edit manually.'; \
	echo '# Source this to enter the evo-memory environment:'; \
	echo '#   source activate.sh'; \
	echo ''; \
	echo '_REPO="$$(cd "$$(dirname "$${BASH_SOURCE[0]:-$$0}")" && pwd)"'; \
	echo '_VENV="$${_REPO}/venv"'; \
	echo ''; \
	echo 'if [ ! -d "$${_VENV}" ]; then'; \
	echo '    echo "ERROR: venv not found. Run make setup-local (or the appropriate target) first."'; \
	echo '    return 1 2>/dev/null || exit 1'; \
	echo 'fi'; \
	echo ''; \
	echo 'source "$${_VENV}/bin/activate"'; \
	echo ''; \
	echo 'if [ -f "$${_REPO}/.env" ]; then'; \
	echo '    set -a; source "$${_REPO}/.env"; set +a'; \
	echo 'fi'; \
	echo ''; \
	echo 'export HF_HOME="$${HF_CACHE_DIR:-$${_REPO}/.hf_cache}"'; \
	echo 'export GCS_BUCKET="$${GCS_BUCKET:-statistical-nlp}"'; \
	echo 'export GCS_PROJECT="$${GCS_PROJECT:-statistical-nlp}"'; \
	echo ''; \
	echo 'if [ -e /dev/accel0 ] || [ -d /dev/vfio ]; then'; \
	echo '    export PJRT_DEVICE=TPU'; \
	echo '    export VM_ID="$${VM_ID:-$$(hostname)}"'; \
	echo '    export XLA_PERSISTENT_CACHE_PATH="$${_REPO}/.xla_cache"'; \
	echo '    mkdir -p "$${XLA_PERSISTENT_CACHE_PATH}" 2>/dev/null'; \
	echo 'else'; \
	echo '    export CUDA_VISIBLE_DEVICES="$${CUDA_VISIBLE_DEVICES:-0}"'; \
	echo 'fi'; \
	echo ''; \
	echo 'cd "$${_REPO}"'; \
	echo 'echo "Activated: venv=$${_VENV}, cwd=$$(pwd)"'; \
	echo 'unset _REPO _VENV'; \
	} > $@
	@chmod +x $@

# ── activate.csh generation (UCL csh/tcsh) ───────────────────────────────────
$(REPO_DIR)/activate.csh: $(STAMPS)/venv
	@echo "Generating activate.csh ..."
	@{ \
	echo '#!/bin/tcsh'; \
	echo '# Auto-generated by Makefile — do not edit manually.'; \
	echo '# Source this to enter the evo-memory environment:'; \
	echo '#   source activate.csh'; \
	echo ''; \
	echo 'set _REPO = "$$cwd"'; \
	echo 'set _VENV = "$${_REPO}/venv"'; \
	echo ''; \
	echo 'if (! -d "$${_VENV}") then'; \
	echo '    echo "ERROR: venv not found. Run make setup-ucl-gpu first."'; \
	echo '    exit 1'; \
	echo 'endif'; \
	echo ''; \
	echo 'source "$${_VENV}/bin/activate.csh"'; \
	echo ''; \
	echo 'if (! $$?HF_CACHE_DIR) then'; \
	echo '    setenv HF_HOME "$${_REPO}/.hf_cache"'; \
	echo 'else'; \
	echo '    setenv HF_HOME "$$HF_CACHE_DIR"'; \
	echo 'endif'; \
	echo 'if (! $$?CUDA_VISIBLE_DEVICES) setenv CUDA_VISIBLE_DEVICES 0'; \
	echo 'if (! $$?GCS_BUCKET)           setenv GCS_BUCKET statistical-nlp'; \
	echo 'if (! $$?GCS_PROJECT)          setenv GCS_PROJECT statistical-nlp'; \
	echo ''; \
	echo 'echo "Activated: venv=$${_VENV}, GPU=$${CUDA_VISIBLE_DEVICES}, cwd=`pwd`"'; \
	} > $@

# =============================================================================
#  Public targets — one per hardware environment
# =============================================================================

## setup-base: internal shared setup (venv + deps + activation scripts)
.PHONY: setup-base
setup-base: $(STAMPS)/base $(REPO_DIR)/activate.sh $(REPO_DIR)/activate.csh
	@mkdir -p $(HF_CACHE_DIR)
	@echo ""
	@echo "Base setup complete."

# ── TPU ───────────────────────────────────────────────────────────────────────
.PHONY: setup-tpu
setup-tpu: $(STAMPS)/venv  ## Google Cloud TPU VM (installs torch-xla, syncs XLA cache)
	@echo "============================================================"
	@echo " evo-memory — TPU Setup"
	@echo "============================================================"
	@# System deps (best-effort — needs passwordless sudo)
	@if sudo -n true 2>/dev/null; then \
	    echo "Installing system packages ..."; \
	    sudo apt-get update -qq; \
	    sudo apt-get install -y -qq libopenblas-dev python3.10-venv >/dev/null 2>&1; \
	fi
	@echo "Installing PyTorch + XLA ..."
	$(PIP) install torch torch_xla[tpu] \
	    -f https://storage.googleapis.com/libtpu-releases/index.html -q
	@echo "Installing shared deps (non-torch) ..."
	$(FILTER_NON_TORCH) | $(PIP) install -q -r /dev/stdin
	@mkdir -p $(STAMPS) && touch $(STAMPS)/base
	@$(MAKE) --no-print-directory _activate-scripts
	@$(MAKE) --no-print-directory _verify-imports
	@mkdir -p $(XLA_CACHE)
	@echo ""
	@echo "Syncing XLA cache from GCS ..."
	@if command -v gsutil &>/dev/null; then \
	    gsutil -m rsync -r "gs://$(GCS_BUCKET)/xla_cache" $(XLA_CACHE) 2>/dev/null || true; \
	else \
	    echo "  gsutil not found — skipping cache sync."; \
	fi
	@$(MAKE) --no-print-directory _summary MODE=tpu

# ── GPU (standard CUDA, including pinning) ────────────────────────────────────
.PHONY: setup-gpu
setup-gpu: setup-base  ## CUDA GPU (use GPU=N to pin a device)
	@echo "============================================================"
	@echo " evo-memory — GPU Setup"
	@echo "============================================================"
	@echo "Installing PyTorch (CUDA 12.1) ..."
	$(PIP) install -q -r $(REQUIREMENTS)
	@if [ -n "$(GPU)" ]; then \
	    echo "Pinned to GPU $(GPU)."; \
	    echo "export CUDA_VISIBLE_DEVICES=$(GPU)" >> $(REPO_DIR)/.env; \
	elif command -v nvidia-smi &>/dev/null; then \
	    _GPU=$$(nvidia-smi --query-gpu=index --format=csv,noheader | head -1 | tr -d ' '); \
	    echo "Detected GPU $${_GPU}."; \
	fi
	@$(MAKE) --no-print-directory _verify-imports
	@$(MAKE) --no-print-directory _summary MODE=gpu

# ── UCL CSH cluster ──────────────────────────────────────────────────────────
.PHONY: setup-ucl-gpu
setup-ucl-gpu: setup-base  ## UCL CSH cluster (GPU, skips GCS and wandb)
	@echo "============================================================"
	@echo " evo-memory — UCL GPU Setup"
	@echo "============================================================"
	@echo "Loading CUDA environment module (if available) ..."
	@bash -c 'source /etc/profile.d/modules.sh 2>/dev/null && module load cuda 2>/dev/null' || true
	@echo "Installing PyTorch (CUDA 12.1) ..."
	$(PIP) install -q -r $(REQUIREMENTS)
	@$(MAKE) --no-print-directory _generate-activate-csh
	@$(MAKE) --no-print-directory _verify-imports
	@echo ""
	@echo "Setup complete."
	@echo "Activate with:  source activate.csh"
	@echo "Then run:       huggingface-cli login"

# ── Local / CPU ───────────────────────────────────────────────────────────────
.PHONY: setup-local
setup-local: setup-base  ## Local or CPU-only (also works if CUDA is present)
	@echo "============================================================"
	@echo " evo-memory — Local Setup"
	@echo "============================================================"
	@echo "Installing PyTorch ..."
	$(PIP) install -q -r $(REQUIREMENTS)
	@$(MAKE) --no-print-directory _verify-imports
	@$(MAKE) --no-print-directory _summary MODE=local

# =============================================================================
#  Optional service logins — call individually as needed
# =============================================================================

.PHONY: hf-login
hf-login:  ## Log in to HuggingFace (required for gated LLaMA 3.2 access)
	@if $(PYTHON) -c "from huggingface_hub import HfFolder; assert HfFolder.get_token()" 2>/dev/null; then \
	    echo "Already logged into HuggingFace."; \
	else \
	    echo "Token page: https://huggingface.co/settings/tokens"; \
	    $(VENV_DIR)/bin/huggingface-cli login; \
	fi

.PHONY: wandb-login
wandb-login:  ## Log in to Weights & Biases
	@if $(PYTHON) -c "import wandb; wandb.api.api_key" 2>/dev/null; then \
	    echo "Already logged into wandb."; \
	else \
	    echo "API key page: https://wandb.ai/authorize"; \
	    $(VENV_DIR)/bin/wandb login || true; \
	fi

.PHONY: gcs-auth
gcs-auth:  ## Authenticate with Google Cloud Storage
	@if ! command -v gcloud &>/dev/null; then \
	    echo "gcloud CLI not found — installing ..."; \
	    curl -fsSL https://sdk.cloud.google.com \
	        | bash -s -- --disable-prompts --install-dir="$$HOME/.local" 2>&1 | tail -5; \
	    export PATH="$$HOME/.local/google-cloud-sdk/bin:$$PATH"; \
	fi
	@if gcloud auth application-default print-access-token &>/dev/null 2>&1; then \
	    echo "Already authenticated with GCS."; \
	else \
	    gcloud auth application-default login \
	        --project $(GCS_PROJECT) --no-launch-browser; \
	fi
	@if gsutil ls "gs://$(GCS_BUCKET)/" &>/dev/null 2>&1; then \
	    echo "gs://$(GCS_BUCKET)/ accessible."; \
	else \
	    echo "WARNING: Cannot access gs://$(GCS_BUCKET)/."; \
	fi

.PHONY: install-claude
install-claude:  ## Install Claude Code CLI
	@if command -v claude &>/dev/null; then \
	    echo "Claude Code already installed ($$(claude --version 2>/dev/null || echo 'unknown'))."; \
	else \
	    if command -v npm &>/dev/null; then \
	        npm install -g @anthropic-ai/claude-code 2>&1 | tail -3; \
	    elif command -v node &>/dev/null; then \
	        curl -fsSL https://npmjs.org/install.sh | sh; \
	        npm install -g @anthropic-ai/claude-code 2>&1 | tail -3; \
	    else \
	        echo "Node.js not found — installing via nvm ..."; \
	        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash; \
	        export NVM_DIR="$$HOME/.nvm"; \
	        . "$$NVM_DIR/nvm.sh"; \
	        nvm install --lts; \
	        npm install -g @anthropic-ai/claude-code 2>&1 | tail -3; \
	    fi; \
	    echo "Done."; \
	fi

.PHONY: logins
logins: hf-login wandb-login gcs-auth  ## Run all three service logins

# =============================================================================
#  TPU helpers
# =============================================================================

.PHONY: tpu-restart-v6e
tpu-restart-v6e:  ## Restart preempted spot v6e-8 VM (europe-west4-a)
	@$(MAKE) --no-print-directory _tpu-restart \
	    TPU_NAME=hyperscale-v6e ZONE=europe-west4-a \
	    ACCELERATOR=v6e-8 RUNTIME=v2-alpha-tpuv6e \
	    SSH_HOST=gcp-tpu-v6e CREATE_FLAGS="--spot --preemptible"

.PHONY: tpu-restart-v4
tpu-restart-v4:  ## Restart on-demand v4-8 VM (us-central2-b)
	@$(MAKE) --no-print-directory _tpu-restart \
	    TPU_NAME=hyperscale-v4 ZONE=us-central2-b \
	    ACCELERATOR=v4-8 RUNTIME=tpu-vm-tf-2.17.0-pjrt \
	    SSH_HOST=gcp-tpu-v4 CREATE_FLAGS=""

# Internal parameterised TPU restart
.PHONY: _tpu-restart
_tpu-restart:
	@echo "TPU: $(TPU_NAME) / $(ZONE) / $(ACCELERATOR)"
	@STATUS=$$(gcloud compute tpus tpu-vm describe $(TPU_NAME) \
	    --zone=$(ZONE) --format="get(state)" 2>/dev/null || echo "NOT_FOUND"); \
	HEALTH=$$(gcloud compute tpus tpu-vm describe $(TPU_NAME) \
	    --zone=$(ZONE) --format="get(health)" 2>/dev/null || echo "UNKNOWN"); \
	echo "Status: $${STATUS}  Health: $${HEALTH}"; \
	if [ "$${STATUS}" = "READY" ] && [ "$${HEALTH}" != "UNHEALTHY_MAINTENANCE" ]; then \
	    IP=$$(gcloud compute tpus tpu-vm describe $(TPU_NAME) \
	        --zone=$(ZONE) \
	        --format="get(networkEndpoints[0].accessConfig.externalIp)"); \
	    echo "Already running at $${IP}"; \
	    sed -i '' "/Host $(SSH_HOST)$$/,/HostName /{s/HostName .*/HostName $${IP}/;}" $$HOME/.ssh/config; \
	    echo "SSH config updated. Run: ssh $(SSH_HOST)"; \
	    exit 0; \
	fi; \
	if [ "$${STATUS}" != "NOT_FOUND" ]; then \
	    echo "Deleting TPU (state: $${STATUS}) ..."; \
	    gcloud compute tpus tpu-vm delete $(TPU_NAME) --zone=$(ZONE) --quiet; \
	fi; \
	echo "Creating TPU ..."; \
	gcloud compute tpus tpu-vm create $(TPU_NAME) \
	    --zone=$(ZONE) --accelerator-type=$(ACCELERATOR) \
	    --version=$(RUNTIME) $(CREATE_FLAGS); \
	IP=$$(gcloud compute tpus tpu-vm describe $(TPU_NAME) \
	    --zone=$(ZONE) \
	    --format="get(networkEndpoints[0].accessConfig.externalIp)"); \
	echo "New IP: $${IP}"; \
	sed -i '' "/Host $(SSH_HOST)$$/,/HostName /{s/HostName .*/HostName $${IP}/;}" $$HOME/.ssh/config; \
	ssh-keygen -R "$${IP}" 2>/dev/null || true; \
	gcloud compute tpus tpu-vm ssh $(TPU_NAME) --zone=$(ZONE) --command="echo 'SSH OK'"; \
	echo "Done. Run: ssh $(SSH_HOST)"

# =============================================================================
#  Smoke test
# =============================================================================

.PHONY: smoke
smoke:  ## Quick smoke test (ES, no NAMM, 2 iterations)
	$(PYTHON) scripts/run_es.py \
	    --run_name smoke --num_iterations 2 \
	    --population_size 2 --mini_batch_size 2 --no-gcs

# =============================================================================
#  Cleanup
# =============================================================================

.PHONY: clean
clean:  ## Remove venv, caches, and stamp files
	rm -rf $(VENV_DIR) $(STAMPS) $(REPO_DIR)/.xla_cache
	rm -f  $(REPO_DIR)/activate.sh $(REPO_DIR)/activate.csh
	@echo "Cleaned."

.PHONY: clean-cache
clean-cache:  ## Remove only HF and XLA caches (keep venv)
	rm -rf $(HF_CACHE_DIR) $(XLA_CACHE)
	@echo "Caches removed."

# =============================================================================
#  Internal helpers
# =============================================================================

.PHONY: _activate-scripts
_activate-scripts: $(REPO_DIR)/activate.sh $(REPO_DIR)/activate.csh

.PHONY: _generate-activate-csh
_generate-activate-csh: $(REPO_DIR)/activate.csh

.PHONY: _verify-imports
_verify-imports:
	@echo "Verifying imports ..."
	@$(PYTHON) -c "from es_finetuning import ESTrainer, ESConfig; print('  imports OK')"
	@echo "  Python: $$($(PYTHON) --version)"
	@echo "  torch:  $$($(PYTHON) -c 'import torch; print(torch.__version__)')"

.PHONY: _summary
_summary:
	@echo ""
	@echo "============================================================"
	@echo " Setup complete!  ($(MODE))"
	@echo "============================================================"
	@echo "Repo:  $(REPO_DIR)"
	@echo "venv:  $(VENV_DIR)"
	@echo ""
	@echo "Activate in new shells:"
	@echo "  source activate.sh"
	@echo ""
	@echo "Smoke test:"
	@echo "  make smoke"

# =============================================================================
#  Help
# =============================================================================

.PHONY: help
help:  ## Show this help message
	@echo "evo-memory — available targets"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	    | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'
	@echo ""
	@echo "Examples:"
	@echo "  make setup-local                # CPU or local GPU"
	@echo "  make setup-gpu GPU=2            # pin to GPU 2"
	@echo "  make setup-tpu                  # Google Cloud TPU VM"
	@echo "  make setup-ucl-gpu              # UCL CSH cluster"
	@echo "  make logins                     # HF + wandb + GCS in one step"
	@echo "  make smoke                      # quick end-to-end test"
