#!/usr/bin/env python3
"""
Analysis 6: Token Importance Alignment (M1 vs M3)
==========================================================
Loads pre-computed NAMM-score-vs-attention alignment data from
data/maskfix_alignment_data.json and generates three plots. No GPU required.

Produces (in analysis/report_6/plots/):
  1. score_attention_correlation.png -- Spearman rho per layer (M1 vs M3)
  2. eviction_regret.png             -- attention mass lost to evicted tokens
  3. alignment_shift.png             -- per-task M1 vs M3 alignment comparison

Run with:
    PYTHONPATH=. .venv/bin/python analysis/report_6/scripts/generate_plots.py
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# =============================================================================
# CONFIG
# =============================================================================
# Data was generated by:
#     PYTHONPATH=. .venv/bin/python analysis/report_6/scripts/generate_data.py
#
# That script loads checkpoints on GPU, runs forward passes to extract
# full-context attention weights, then calls the NAMM scoring network to
# get token importance scores and eviction decisions. Spearman rank
# correlation and eviction regret are computed per layer per sample.
#
# Checkpoint paths used during data generation:
#   M1 LoRA:          experiment_artifacts/gcs/M1/best_ckpt.pt
#   M3 LoRA:  experiment_artifacts/gcs/M3_cs1024_maskfix/best_ckpt.pt
#   M2 NAMM:          experiment_artifacts/gcs/M2_cs1024_maskfix/ckpt.pt
#
# To regenerate maskfix_alignment_data.json, re-run the GPU script above.
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
REPORT_DIR = SCRIPT_DIR.parent
DATA_FILE = REPORT_DIR / "data" / "maskfix_alignment_data.json"
PLOT_DIR = REPORT_DIR / "plots"

NUM_LAYERS = 16

# Plot style
plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 150,
    "font.size": 11,
    "axes.titlesize": 13,
    "axes.labelsize": 12,
})

# Condition styling
COLORS = {"M1": "#d62728", "M2": "#ff7f0e", "M3": "#1f77b4"}
LABELS = {
    "M1": "M1 (full context)",
    "M2": "M2 (NAMM only, no LoRA)",
    "M3": "M3 (LoRA + NAMM)",
}
CONDITION_ORDER = ["M1", "M2", "M3"]


# =============================================================================
# LOAD DATA
# =============================================================================

def load_data() -> dict:
    """Load the pre-computed alignment data.

    Expected structure:
        {
            "cache_size": 1024,
            "conditions": {
                "M1": {
                    "samples": [
                        {
                            "task": str,
                            "idx": int,
                            "seq_len": int,
                            "layers": [
                                {
                                    "layer_id": int,
                                    "spearman_rho": float,
                                    "total_regret": float,
                                    "mean_regret": float,
                                    "num_tokens": int,
                                    "num_retained": int,
                                    "num_evicted": int,
                                },
                                ...  (16 layers)
                            ]
                        },
                        ...
                    ]
                },
                "M3": { ... same structure ... }
            }
        }
    """
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Data file not found: {DATA_FILE}\n"
            "Generate it with: PYTHONPATH=. .venv/bin/python "
            "analysis/report_6/scripts/generate_data.py"
        )
    with open(DATA_FILE) as f:
        data = json.load(f)

    conditions = data.get("conditions", {})
    # Normalise legacy key "M3_maskfix" -> "M3"
    if "M3_maskfix" in conditions and "M3" not in conditions:
        conditions["M3"] = conditions.pop("M3_maskfix")
    print(f"Loaded data from {DATA_FILE}")
    print(f"  cache_size: {data.get('cache_size', '?')}")
    for cond, cdata in conditions.items():
        n = len(cdata.get("samples", []))
        print(f"  {cond}: {n} samples")
    return data


# =============================================================================
# HELPER: Aggregate per-layer statistics
# =============================================================================

def aggregate_by_layer(
    conditions: dict, metric: str
) -> dict[str, tuple[list[int], list[float], list[float]]]:
    """Aggregate a metric across samples, grouped by layer.

    Returns:
        {condition_name: (layers, means, stds)}
    """
    result = {}
    for cond_name in CONDITION_ORDER:
        if cond_name not in conditions:
            continue
        layer_vals: dict[int, list[float]] = {}
        for sample in conditions[cond_name]["samples"]:
            for ld in sample["layers"]:
                val = ld[metric]
                if not np.isnan(val):
                    layer_vals.setdefault(ld["layer_id"], []).append(val)
        if not layer_vals:
            continue
        layers = sorted(layer_vals.keys())
        means = [float(np.mean(layer_vals[l])) for l in layers]
        stds = [float(np.std(layer_vals[l])) for l in layers]
        result[cond_name] = (layers, means, stds)
    return result


# =============================================================================
# PLOT 1: Score-Attention Correlation
# =============================================================================

def plot_score_attention_correlation(conditions: dict) -> None:
    """Spearman rank correlation between NAMM scores and attention importance."""
    agg = aggregate_by_layer(conditions, "spearman_rho")

    fig, ax = plt.subplots(figsize=(12, 6))

    for cond_name, (layers, means, stds) in agg.items():
        color = COLORS.get(cond_name, "#333")
        label = LABELS.get(cond_name, cond_name)
        ax.plot(layers, means, "-o", color=color, label=label,
                linewidth=2, markersize=5)
        ax.fill_between(layers,
                        [m - s for m, s in zip(means, stds)],
                        [m + s for m, s in zip(means, stds)],
                        alpha=0.15, color=color)

    ax.axhline(0, color="grey", linestyle=":", alpha=0.5)
    ax.set_xlabel("Layer")
    ax.set_ylabel("Spearman Rank Correlation")
    ax.set_title("NAMM Score vs Attention Importance Alignment\n"
                 "(Spearman rho per layer, averaged across test samples)")
    ax.set_xticks(range(NUM_LAYERS))
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    out = PLOT_DIR / "score_attention_correlation.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 2: Eviction Regret
# =============================================================================

def plot_eviction_regret(conditions: dict) -> None:
    """Total and per-token attention mass lost to evicted tokens per layer."""
    agg_total = aggregate_by_layer(conditions, "total_regret")
    agg_mean = aggregate_by_layer(conditions, "mean_regret")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    for cond_name in CONDITION_ORDER:
        color = COLORS.get(cond_name, "#333")
        label = LABELS.get(cond_name, cond_name)

        if cond_name in agg_total:
            layers, means, stds = agg_total[cond_name]
            ax1.plot(layers, means, "-o", color=color, label=label,
                     linewidth=2, markersize=5)
            ax1.fill_between(layers,
                             [m - s for m, s in zip(means, stds)],
                             [m + s for m, s in zip(means, stds)],
                             alpha=0.15, color=color)

        if cond_name in agg_mean:
            layers, means, stds = agg_mean[cond_name]
            ax2.plot(layers, means, "-o", color=color, label=label,
                     linewidth=2, markersize=5)
            ax2.fill_between(layers,
                             [m - s for m, s in zip(means, stds)],
                             [m + s for m, s in zip(means, stds)],
                             alpha=0.15, color=color)

    ax1.set_xlabel("Layer")
    ax1.set_ylabel("Total Attention Mass on Evicted Tokens")
    ax1.set_title("Eviction Regret (Total)")
    ax1.set_xticks(range(NUM_LAYERS))
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.set_xlabel("Layer")
    ax2.set_ylabel("Mean Attention per Evicted Token")
    ax2.set_title("Eviction Regret (Per Token)")
    ax2.set_xticks(range(NUM_LAYERS))
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    fig.suptitle("Eviction Regret: Attention Mass Lost to Evicted Tokens",
                 fontsize=14, y=1.02)
    fig.tight_layout()
    out = PLOT_DIR / "eviction_regret.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 3: Alignment Shift (per-task M1 vs M3)
# =============================================================================

def plot_alignment_shift(conditions: dict) -> None:
    """Per-task bar chart comparing mean Spearman rho between M1 and M3."""
    task_cond_rhos: dict[str, dict[str, list[float]]] = {}
    for cond_name in CONDITION_ORDER:
        if cond_name not in conditions:
            continue
        for sample in conditions[cond_name]["samples"]:
            rhos = [ld["spearman_rho"] for ld in sample["layers"]
                    if not np.isnan(ld["spearman_rho"])]
            if rhos:
                task_cond_rhos.setdefault(sample["task"], {}).setdefault(
                    cond_name, []).append(float(np.mean(rhos)))

    if not task_cond_rhos:
        print("  WARNING: No per-task data, skipping alignment_shift plot")
        return

    task_names = sorted(task_cond_rhos.keys())
    x = np.arange(len(task_names))
    width = 0.35

    task_display = {
        "qasper": "Qasper",
        "2wikimqa": "2WikiMQA",
        "qasper_e": "Qasper-E",
        "hotpotqa_e": "HotpotQA-E",
        "2wikimqa_e": "2WikiMQA-E",
    }

    fig, ax = plt.subplots(figsize=(10, 6))

    for i, cond_name in enumerate(CONDITION_ORDER):
        if cond_name not in conditions:
            continue
        vals = []
        errs = []
        for t in task_names:
            rho_list = task_cond_rhos.get(t, {}).get(cond_name, [])
            vals.append(float(np.mean(rho_list)) if rho_list else 0.0)
            errs.append(float(np.std(rho_list)) if rho_list else 0.0)

        color = COLORS.get(cond_name, "#333")
        label = LABELS.get(cond_name, cond_name)
        ax.bar(x + i * width, vals, width, yerr=errs,
               label=label, color=color, edgecolor="white", capsize=3)

    ax.set_xticks(x + width / 2)
    ax.set_xticklabels([task_display.get(t, t) for t in task_names])
    ax.axhline(0, color="grey", linestyle=":", alpha=0.5)
    ax.set_ylabel("Mean Spearman rho (NAMM score vs attention)")
    ax.set_title("Alignment Shift: M1 vs M3\n"
                 "(Does M3 fine-tuning improve NAMM-attention alignment?)")
    ax.legend()
    ax.grid(True, alpha=0.3, axis="y")
    fig.tight_layout()
    out = PLOT_DIR / "alignment_shift.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# SUMMARY
# =============================================================================

def print_summary(conditions: dict) -> None:
    """Print summary statistics to stdout."""
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)

    for cond_name in CONDITION_ORDER:
        if cond_name not in conditions:
            continue
        all_rhos = []
        all_total_regret = []
        all_mean_regret = []
        for sample in conditions[cond_name]["samples"]:
            for ld in sample["layers"]:
                if not np.isnan(ld["spearman_rho"]):
                    all_rhos.append(ld["spearman_rho"])
                all_total_regret.append(ld["total_regret"])
                all_mean_regret.append(ld["mean_regret"])

        label = LABELS.get(cond_name, cond_name)
        print(f"\n  {label}:")
        print(f"    Spearman rho: mean={np.mean(all_rhos):.4f}, "
              f"std={np.std(all_rhos):.4f}, n={len(all_rhos)}")
        print(f"    Total regret: mean={np.mean(all_total_regret):.4f}, "
              f"std={np.std(all_total_regret):.4f}")
        print(f"    Mean regret:  mean={np.mean(all_mean_regret):.6f}, "
              f"std={np.std(all_mean_regret):.6f}")


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    data = load_data()
    conditions = data.get("conditions", {})

    if not conditions:
        raise RuntimeError("No condition data found in JSON file")

    PLOT_DIR.mkdir(parents=True, exist_ok=True)

    print("\nGenerating plots...")
    plot_score_attention_correlation(conditions)
    plot_eviction_regret(conditions)
    plot_alignment_shift(conditions)

    print_summary(conditions)
    print("\nDone. All plots saved to:", PLOT_DIR)


if __name__ == "__main__":
    main()
