#!/usr/bin/env python3
"""
Analysis 4: LoRA Weight Comparison (M1 vs M3 maskfix)
=====================================================
Loads pre-computed weight analysis data from maskfix_data.npz and generates
four comparison plots. No GPU required.

Produces (in analysis/report_4/):
  1. weight_magnitude.png  -- per-layer ||B@A||_F for q_proj and v_proj
  2. singular_values.png   -- SVD spectra of B@A (q_proj) per layer, 4x4 grid
  3. subspace_overlap.png  -- cosine of principal angles between M1/M3 subspaces
  4. norm_ratio.png        -- ||M3||_F / ||M1||_F ratio per layer

Run with:
    PYTHONPATH=. .venv/bin/python analysis/report_4/generate_plots.py
"""

from __future__ import annotations

import os
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# =============================================================================
# CONFIG
# =============================================================================
# Data was generated by:
#     PYTHONPATH=. .venv/bin/python analysis/run_maskfix_gpu_analyses.py
#
# That script loads two checkpoints on GPU and computes LoRA B@A products,
# Frobenius norms, SVD spectra, and subspace overlaps. The results are saved
# to the .npz file below.
#
# Checkpoint paths used during data generation:
#   M1 LoRA:          experiment_artifacts/gcs/M1/best_ckpt.pt
#   M3 maskfix LoRA:  experiment_artifacts/gcs/M3_cs1024_maskfix/best_ckpt.pt
#
# To regenerate maskfix_data.npz, re-run the GPU script above.
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
DATA_FILE = SCRIPT_DIR / "maskfix_data.npz"
PLOT_DIR = SCRIPT_DIR

NUM_LAYERS = 16
RANK = 8
PROJS = ["q_proj", "v_proj"]

# Plot style
plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 150,
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
})
M1_COLOR = "#2196F3"
M3_COLOR = "#FF5722"


# =============================================================================
# LOAD DATA
# =============================================================================

def load_data() -> dict[str, np.ndarray]:
    """Load the pre-computed maskfix weight analysis data."""
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Data file not found: {DATA_FILE}\n"
            "Generate it with: PYTHONPATH=. .venv/bin/python "
            "analysis/run_maskfix_gpu_analyses.py"
        )
    data = dict(np.load(DATA_FILE))
    print(f"Loaded {len(data)} arrays from {DATA_FILE}")
    return data


# =============================================================================
# PLOT 1: Weight Magnitude
# =============================================================================

def plot_weight_magnitude(data: dict[str, np.ndarray]) -> None:
    """Per-layer Frobenius norm of B@A for q_proj and v_proj."""
    layers = np.arange(NUM_LAYERS)
    fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=False)

    for ax, proj in zip(axes, PROJS):
        m1_norms = data[f"m1_norms_{proj}"]
        m3_norms = data[f"m3_maskfix_norms_{proj}"]
        width = 0.35

        ax.bar(layers - width / 2, m1_norms, width,
               label="M1 (full ctx)", color=M1_COLOR, alpha=0.85)
        ax.bar(layers + width / 2, m3_norms, width,
               label="M3 maskfix", color=M3_COLOR, alpha=0.85)
        ax.set_xlabel("Layer")
        ax.set_ylabel("||B @ A||_F")
        ax.set_title(f"Effective LoRA Update Norm -- {proj}")
        ax.set_xticks(layers)
        ax.legend()
        ax.grid(axis="y", alpha=0.3)

    fig.suptitle("Per-Layer LoRA Weight Magnitude: M1 vs M3 maskfix",
                 fontsize=13, fontweight="bold")
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    out = PLOT_DIR / "weight_magnitude.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 2: Singular Values (q_proj, 4x4 grid)
# =============================================================================

def plot_singular_values(data: dict[str, np.ndarray]) -> None:
    """SVD spectra of B@A (q_proj) per layer in a 4x4 grid."""
    m1_sv = data["m1_sv_q_proj"]       # (16, 8)
    m3_sv = data["m3_maskfix_sv_q_proj"]  # (16, 8)

    fig, axes = plt.subplots(4, 4, figsize=(14, 12), sharex=True)
    axes_flat = axes.flatten()

    for layer in range(NUM_LAYERS):
        ax = axes_flat[layer]
        sv_m1 = m1_sv[layer]
        sv_m3 = m3_sv[layer]
        x = np.arange(1, len(sv_m1) + 1)

        ax.bar(x - 0.2, sv_m1, 0.4,
               label="M1" if layer == 0 else None,
               color=M1_COLOR, alpha=0.85)
        ax.bar(x + 0.2, sv_m3, 0.4,
               label="M3 maskfix" if layer == 0 else None,
               color=M3_COLOR, alpha=0.85)
        ax.set_title(f"Layer {layer}", fontsize=9)
        ax.set_xticks(x)
        if layer >= 12:
            ax.set_xlabel("SV index")
        if layer % 4 == 0:
            ax.set_ylabel("Singular value")
        ax.grid(axis="y", alpha=0.3)

    fig.suptitle("Singular Value Spectrum of B@A (q_proj): M1 vs M3 maskfix",
                 fontsize=13, fontweight="bold")
    fig.legend(["M1 (full ctx)", "M3 maskfix"], loc="upper right", fontsize=10)
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    out = PLOT_DIR / "singular_values.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 3: Subspace Overlap
# =============================================================================

def plot_subspace_overlap(data: dict[str, np.ndarray]) -> None:
    """Mean cosine of principal angles between M1 and M3 LoRA column spaces."""
    layers = np.arange(NUM_LAYERS)
    overlap_q = data["overlap_maskfix_q_proj"]
    overlap_v = data["overlap_maskfix_v_proj"]

    fig, ax = plt.subplots(figsize=(10, 5))
    width = 0.35
    ax.bar(layers - width / 2, overlap_q, width,
           label="q_proj", color=M1_COLOR, alpha=0.85)
    ax.bar(layers + width / 2, overlap_v, width,
           label="v_proj", color=M3_COLOR, alpha=0.85)
    ax.set_xlabel("Layer")
    ax.set_ylabel("Mean cosine of principal angles")
    ax.set_title("Subspace Overlap Between M1 and M3 maskfix LoRA Column Spaces",
                 fontsize=12, fontweight="bold")
    ax.set_xticks(layers)
    ax.set_ylim(0, 1.05)
    ax.axhline(1.0, color="grey", linestyle="--", linewidth=0.8, alpha=0.5)
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    out = PLOT_DIR / "subspace_overlap.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 4: Norm Ratio
# =============================================================================

def plot_norm_ratio(data: dict[str, np.ndarray]) -> None:
    """||M3 B@A||_F / ||M1 B@A||_F ratio per layer."""
    layers = np.arange(NUM_LAYERS)
    ratio_q = data["ratio_maskfix_q_proj"]
    ratio_v = data["ratio_maskfix_v_proj"]

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(layers, ratio_q, "o-", color=M1_COLOR, label="q_proj",
            markersize=7, linewidth=2)
    ax.plot(layers, ratio_v, "s-", color=M3_COLOR, label="v_proj",
            markersize=7, linewidth=2)
    ax.axhline(1.0, color="grey", linestyle="--", linewidth=1, alpha=0.6,
               label="ratio = 1 (equal)")
    ax.set_xlabel("Layer")
    ax.set_ylabel("||M3 B@A||_F / ||M1 B@A||_F")
    ax.set_title("Norm Ratio (M3 maskfix / M1): Which Layers Work Harder Under Eviction?",
                 fontsize=12, fontweight="bold")
    ax.set_xticks(layers)
    ax.legend()
    ax.grid(alpha=0.3)
    fig.tight_layout()
    out = PLOT_DIR / "norm_ratio.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# SUMMARY
# =============================================================================

def print_summary(data: dict[str, np.ndarray]) -> None:
    """Print summary statistics to stdout."""
    print("\n" + "=" * 80)
    print("SUMMARY TABLES")
    print("=" * 80)

    for proj in PROJS:
        m1_norms = data[f"m1_norms_{proj}"]
        m3_norms = data[f"m3_maskfix_norms_{proj}"]
        ratio = data[f"ratio_maskfix_{proj}"]
        overlap = data[f"overlap_maskfix_{proj}"]

        print(f"\n--- Per-Layer Frobenius Norms and Ratio ({proj}) ---")
        print(f"{'Layer':>5} | {'M1 ||B@A||_F':>14} | {'M3 ||B@A||_F':>14} | {'Ratio M3/M1':>12}")
        print("-" * 55)
        for i in range(NUM_LAYERS):
            print(f"{i:5d} | {m1_norms[i]:14.6f} | {m3_norms[i]:14.6f} | {ratio[i]:12.4f}")

        print(f"\n  {proj}: ratio mean={ratio.mean():.4f}, std={ratio.std():.4f}, "
              f"min={ratio.min():.4f} (L{ratio.argmin()}), max={ratio.max():.4f} (L{ratio.argmax()})")
        print(f"  {proj}: overlap mean={overlap.mean():.4f}, std={overlap.std():.4f}, "
              f"min={overlap.min():.4f} (L{overlap.argmin()}), max={overlap.max():.4f} (L{overlap.argmax()})")


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    data = load_data()

    print("\nGenerating plots...")
    plot_weight_magnitude(data)
    plot_singular_values(data)
    plot_subspace_overlap(data)
    plot_norm_ratio(data)

    print_summary(data)
    print("\nDone. All plots saved to:", PLOT_DIR)


if __name__ == "__main__":
    main()
