#!/usr/bin/env python3
"""
Analysis 5: Attention Entropy Shift Under Eviction (M1 vs M3 maskfix)
=====================================================================
Loads pre-computed attention entropy/sink data from maskfix_data.npz and
generates three comparison plots. No GPU required.

Produces (in analysis/report_5/plots/):
  1. attention_entropy.png  -- bar chart with entropy + sinks per layer
  2. entropy_heatmap.png    -- 2-panel layer x head heatmaps (M1 and M3)
  3. entropy_diff.png       -- M3-M1 difference heatmap

Run with:
    PYTHONPATH=. .venv/bin/python analysis/report_5/scripts/generate_plots.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# =============================================================================
# CONFIG
# =============================================================================
# Data was generated by:
#     PYTHONPATH=. .venv/bin/python analysis/run_maskfix_gpu_analyses.py
#
# That script loads two checkpoints on GPU, runs forward passes with
# output_attentions=True on test samples, and computes per-layer per-head
# attention entropy and sink fractions. The results are saved to the .npz
# file below.
#
# Checkpoint paths used during data generation:
#   M1 LoRA:          experiment_artifacts/gcs/M1/best_ckpt.pt
#   M3 maskfix LoRA:  experiment_artifacts/gcs/M3_cs1024_maskfix/best_ckpt.pt
#   M2 NAMM:          experiment_artifacts/gcs/M2_cs1024_maskfix/ckpt.pt
#
# To regenerate maskfix_data.npz, re-run the GPU script above.
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
REPORT_DIR = SCRIPT_DIR.parent
DATA_FILE = REPORT_DIR / "data" / "maskfix_data.npz"
PLOT_DIR = REPORT_DIR / "plots"

NUM_LAYERS = 16
NUM_HEADS = 32

# Plot style
plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 150,
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
})
M1_COLOR = "#d62728"
M3_COLOR = "#1f77b4"


# =============================================================================
# LOAD DATA
# =============================================================================

def load_data() -> dict[str, np.ndarray]:
    """Load the pre-computed maskfix attention analysis data.

    Expected keys (used -- ignoring m3bug_ prefix):
        m1_entropy:   (16, 32) -- per-layer per-head mean entropy, M1
        m1_sinks:     (16, 32) -- per-layer per-head mean sink fraction, M1
        m3mf_entropy: (16, 32) -- per-layer per-head mean entropy, M3 maskfix
        m3mf_sinks:   (16, 32) -- per-layer per-head mean sink fraction, M3 maskfix
    """
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Data file not found: {DATA_FILE}\n"
            "Generate it with: PYTHONPATH=. .venv/bin/python "
            "analysis/run_maskfix_gpu_analyses.py"
        )
    data = dict(np.load(DATA_FILE))
    # Validate expected keys
    for key in ["m1_entropy", "m1_sinks", "m3mf_entropy", "m3mf_sinks"]:
        if key not in data:
            raise KeyError(f"Missing expected key '{key}' in {DATA_FILE}")
    print(f"Loaded data from {DATA_FILE}")
    print(f"  m1_entropy:   {data['m1_entropy'].shape}")
    print(f"  m1_sinks:     {data['m1_sinks'].shape}")
    print(f"  m3mf_entropy: {data['m3mf_entropy'].shape}")
    print(f"  m3mf_sinks:   {data['m3mf_sinks'].shape}")
    return data


# =============================================================================
# PLOT 1: Attention Entropy Bar Chart (entropy + sinks per layer)
# =============================================================================

def plot_attention_entropy(data: dict[str, np.ndarray]) -> None:
    """Bar chart showing per-layer mean entropy and sink fraction for M1 vs M3."""
    m1_ent = data["m1_entropy"].mean(axis=1)   # (16,) -- mean across heads
    m3_ent = data["m3mf_entropy"].mean(axis=1)
    m1_snk = data["m1_sinks"].mean(axis=1)
    m3_snk = data["m3mf_sinks"].mean(axis=1)

    layers = np.arange(NUM_LAYERS)
    width = 0.35

    fig, (ax_ent, ax_snk) = plt.subplots(2, 1, figsize=(12, 9), sharex=True)

    # -- Entropy panel --
    ax_ent.bar(layers - width / 2, m1_ent, width,
               label="M1 (full context)", color=M1_COLOR, alpha=0.85)
    ax_ent.bar(layers + width / 2, m3_ent, width,
               label="M3 maskfix (evicted)", color=M3_COLOR, alpha=0.85)
    ax_ent.set_ylabel("Attention Entropy (nats)")
    ax_ent.set_title("Per-Layer Mean Attention Entropy", fontsize=12)
    ax_ent.legend(fontsize=10)
    ax_ent.grid(axis="y", alpha=0.3)

    # -- Sink fraction panel --
    ax_snk.bar(layers - width / 2, m1_snk, width,
               label="M1 (full context)", color=M1_COLOR, alpha=0.85)
    ax_snk.bar(layers + width / 2, m3_snk, width,
               label="M3 maskfix (evicted)", color=M3_COLOR, alpha=0.85)
    ax_snk.set_xlabel("Layer")
    ax_snk.set_ylabel("Attention Mass on First-5 Tokens")
    ax_snk.set_title("Per-Layer Mean Sink Fraction", fontsize=12)
    ax_snk.set_xticks(layers)
    ax_snk.legend(fontsize=10)
    ax_snk.grid(axis="y", alpha=0.3)

    fig.suptitle("Attention Entropy and Sink Analysis: M1 vs M3 maskfix",
                 fontsize=13, fontweight="bold")
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    out = PLOT_DIR / "attention_entropy.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 2: Entropy Heatmap (2-panel: M1 and M3)
# =============================================================================

def plot_entropy_heatmap(data: dict[str, np.ndarray]) -> None:
    """Side-by-side layer x head entropy heatmaps for M1 and M3."""
    m1_ent = data["m1_entropy"]    # (16, 32)
    m3_ent = data["m3mf_entropy"]  # (16, 32)

    # Shared color scale
    vmin = min(m1_ent.min(), m3_ent.min())
    vmax = max(m1_ent.max(), m3_ent.max())

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    im1 = ax1.imshow(m1_ent, aspect="auto", cmap="viridis",
                     vmin=vmin, vmax=vmax, origin="lower")
    ax1.set_xlabel("Head")
    ax1.set_ylabel("Layer")
    ax1.set_title("M1 (full context)", fontsize=12)
    ax1.set_xticks(range(0, NUM_HEADS, 4))
    ax1.set_yticks(range(NUM_LAYERS))

    im2 = ax2.imshow(m3_ent, aspect="auto", cmap="viridis",
                     vmin=vmin, vmax=vmax, origin="lower")
    ax2.set_xlabel("Head")
    ax2.set_ylabel("Layer")
    ax2.set_title("M3 maskfix (evicted)", fontsize=12)
    ax2.set_xticks(range(0, NUM_HEADS, 4))
    ax2.set_yticks(range(NUM_LAYERS))

    fig.suptitle("Per-Head Attention Entropy by Layer: M1 vs M3 maskfix",
                 fontsize=13, fontweight="bold")
    fig.colorbar(im2, ax=[ax1, ax2], label="Entropy (nats)", shrink=0.8)
    out = PLOT_DIR / "entropy_heatmap.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 3: Entropy Difference Heatmap (M3 - M1)
# =============================================================================

def plot_entropy_diff(data: dict[str, np.ndarray]) -> None:
    """Heatmap of M3-M1 entropy difference (layer x head)."""
    diff = data["m3mf_entropy"] - data["m1_entropy"]  # (16, 32)
    abs_max = max(abs(diff.min()), abs(diff.max()))

    fig, ax = plt.subplots(figsize=(10, 6))
    im = ax.imshow(diff, aspect="auto", cmap="RdBu_r",
                   vmin=-abs_max, vmax=abs_max, origin="lower")
    ax.set_xlabel("Head")
    ax.set_ylabel("Layer")
    ax.set_title("Entropy Difference (M3 maskfix - M1)\n"
                 "Red = M3 higher entropy, Blue = M1 higher entropy",
                 fontsize=12, fontweight="bold")
    ax.set_xticks(range(0, NUM_HEADS, 4))
    ax.set_yticks(range(NUM_LAYERS))
    fig.colorbar(im, ax=ax, label="Entropy difference (nats)")
    fig.tight_layout()
    out = PLOT_DIR / "entropy_diff.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# SUMMARY
# =============================================================================

def print_summary(data: dict[str, np.ndarray]) -> None:
    """Print summary statistics to stdout."""
    m1_ent = data["m1_entropy"]
    m3_ent = data["m3mf_entropy"]
    m1_snk = data["m1_sinks"]
    m3_snk = data["m3mf_sinks"]
    diff = m3_ent - m1_ent

    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"\nM1 entropy:  mean={m1_ent.mean():.4f}, std={m1_ent.std():.4f}")
    print(f"M3 entropy:  mean={m3_ent.mean():.4f}, std={m3_ent.std():.4f}")
    print(f"Diff (M3-M1): mean={diff.mean():.4f}, std={diff.std():.4f}, "
          f"min={diff.min():.4f}, max={diff.max():.4f}")
    print(f"\nM1 sinks:  mean={m1_snk.mean():.4f}, std={m1_snk.std():.4f}")
    print(f"M3 sinks:  mean={m3_snk.mean():.4f}, std={m3_snk.std():.4f}")

    print("\n--- Per-Layer Mean Entropy ---")
    print(f"{'Layer':>5} | {'M1':>10} | {'M3 maskfix':>12} | {'Diff':>10}")
    print("-" * 45)
    m1_layer = m1_ent.mean(axis=1)
    m3_layer = m3_ent.mean(axis=1)
    for i in range(NUM_LAYERS):
        print(f"{i:5d} | {m1_layer[i]:10.4f} | {m3_layer[i]:12.4f} | "
              f"{m3_layer[i] - m1_layer[i]:10.4f}")


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    data = load_data()

    print("\nGenerating plots...")
    plot_attention_entropy(data)
    plot_entropy_heatmap(data)
    plot_entropy_diff(data)

    print_summary(data)
    print("\nDone. All plots saved to:", PLOT_DIR)


if __name__ == "__main__":
    main()
