#!/usr/bin/env python3
"""
Analysis 5: Attention Entropy Under Eviction (M1 vs M2 vs M3)
=====================================================================
Loads pre-computed attention entropy data and generates comparison plots.
No GPU required.

Each model is measured in its **actual operating regime**:
  - M1: full-context forward (all tokens visible)
  - M2: NAMM eviction active, no LoRA (base model + NAMM)
  - M3: NAMM eviction active, with LoRA (LoRA + frozen NAMM)

Entropy of evicted models is mathematically equivalent to computing over
the full prompt with evicted positions set to zero (0*log(0) = 0).

Data generated by:
    PYTHONPATH=. .venv/bin/python analysis/report_5/scripts/generate_data.py

Produces (in analysis/report_5/plots/):
  1. attention_entropy.png  -- bar chart: per-layer entropy (M1 vs M2 vs M3)
  2. entropy_heatmap.png    -- 2-panel layer x head heatmaps (M1 vs M3)
  3. entropy_diff.png       -- M3 minus M1 difference heatmap

Run with:
    PYTHONPATH=. .venv/bin/python analysis/report_5/scripts/generate_plots.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# =============================================================================
# CONFIG
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
REPORT_DIR = SCRIPT_DIR.parent
DATA_FILE = REPORT_DIR / "data" / "entropy_data.npz"
PLOT_DIR = REPORT_DIR / "plots"

NUM_LAYERS = 16
NUM_HEADS = 32

plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 150,
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
})
M1_COLOR = "#d62728"
M2_COLOR = "#ff7f0e"
M3_COLOR = "#1f77b4"


# =============================================================================
# LOAD DATA
# =============================================================================

def load_data() -> dict[str, np.ndarray]:
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Data file not found: {DATA_FILE}\n"
            "Generate it with: PYTHONPATH=. .venv/bin/python "
            "analysis/report_5/scripts/generate_data.py"
        )
    data = dict(np.load(DATA_FILE))
    for key in ["m1_entropy", "m3_entropy"]:
        if key not in data:
            raise KeyError(f"Missing expected key '{key}' in {DATA_FILE}")
    print(f"Loaded data from {DATA_FILE}")
    print(f"  m1_entropy:  {data['m1_entropy'].shape}")
    if "m2_entropy" in data:
        print(f"  m2_entropy:  {data['m2_entropy'].shape}")
    print(f"  m3_entropy:  {data['m3_entropy'].shape}")
    if "m3_retention" in data:
        ret = data["m3_retention"]
        print(f"  M3 retention: mean={ret.mean():.3f}, "
              f"range=[{ret.min():.3f}, {ret.max():.3f}]")
    return data


# =============================================================================
# PLOT 1: Attention Entropy Bar Chart (M1 vs M2 vs M3)
# =============================================================================

def plot_attention_entropy(data: dict[str, np.ndarray]) -> None:
    m1_ent = data["m1_entropy"].mean(axis=1)
    m3_ent = data["m3_entropy"].mean(axis=1)
    has_m2 = "m2_entropy" in data
    if has_m2:
        m2_ent = data["m2_entropy"].mean(axis=1)

    layers = np.arange(NUM_LAYERS)
    n_bars = 3 if has_m2 else 2
    width = 0.8 / n_bars

    fig, ax = plt.subplots(figsize=(14, 6))

    if has_m2:
        ax.bar(layers - width, m1_ent, width,
               label="M1 (full context)", color=M1_COLOR, alpha=0.85)
        ax.bar(layers, m2_ent, width,
               label="M2 (NAMM only, no LoRA)", color=M2_COLOR, alpha=0.85)
        ax.bar(layers + width, m3_ent, width,
               label="M3 (LoRA + NAMM)", color=M3_COLOR, alpha=0.85)
    else:
        ax.bar(layers - width / 2, m1_ent, width,
               label="M1 (full context)", color=M1_COLOR, alpha=0.85)
        ax.bar(layers + width / 2, m3_ent, width,
               label="M3 (with eviction)", color=M3_COLOR, alpha=0.85)

    ax.set_xlabel("Layer")
    ax.set_ylabel("Attention Entropy (nats)")
    ax.set_title("Per-Layer Mean Attention Entropy\n"
                 "(each model in its actual operating regime)",
                 fontsize=12, fontweight="bold")
    ax.set_xticks(layers)
    ax.legend(fontsize=10)
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    out = PLOT_DIR / "attention_entropy.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 2: Entropy Heatmap (2-panel: M1 and M3)
# =============================================================================

def plot_entropy_heatmap(data: dict[str, np.ndarray]) -> None:
    m1_ent = data["m1_entropy"]
    m3_ent = data["m3_entropy"]

    vmin = min(m1_ent.min(), m3_ent.min())
    vmax = max(m1_ent.max(), m3_ent.max())

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    ax1.imshow(m1_ent, aspect="auto", cmap="viridis",
               vmin=vmin, vmax=vmax, origin="lower")
    ax1.set_xlabel("Head")
    ax1.set_ylabel("Layer")
    ax1.set_title("M1 (full context)", fontsize=12)
    ax1.set_xticks(range(0, NUM_HEADS, 4))
    ax1.set_yticks(range(NUM_LAYERS))

    im2 = ax2.imshow(m3_ent, aspect="auto", cmap="viridis",
                     vmin=vmin, vmax=vmax, origin="lower")
    ax2.set_xlabel("Head")
    ax2.set_ylabel("Layer")
    ax2.set_title("M3 (with eviction)", fontsize=12)
    ax2.set_xticks(range(0, NUM_HEADS, 4))
    ax2.set_yticks(range(NUM_LAYERS))

    fig.suptitle("Per-Head Attention Entropy by Layer: M1 vs M3",
                 fontsize=13, fontweight="bold")
    fig.colorbar(im2, ax=[ax1, ax2], label="Entropy (nats)", shrink=0.8)
    out = PLOT_DIR / "entropy_heatmap.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 3: Entropy Difference Heatmap (M3 - M1)
# =============================================================================

def plot_entropy_diff(data: dict[str, np.ndarray]) -> None:
    diff = data["m3_entropy"] - data["m1_entropy"]
    abs_max = max(abs(diff.min()), abs(diff.max()))

    fig, ax = plt.subplots(figsize=(10, 6))
    im = ax.imshow(diff, aspect="auto", cmap="RdBu_r",
                   vmin=-abs_max, vmax=abs_max, origin="lower")
    ax.set_xlabel("Head")
    ax.set_ylabel("Layer")
    ax.set_title("Entropy Difference (M3 evicted - M1 full context)\n"
                 "Red = M3 higher entropy, Blue = M1 higher entropy",
                 fontsize=12, fontweight="bold")
    ax.set_xticks(range(0, NUM_HEADS, 4))
    ax.set_yticks(range(NUM_LAYERS))
    fig.colorbar(im, ax=ax, label="Entropy difference (nats)")
    fig.tight_layout()
    out = PLOT_DIR / "entropy_diff.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# PLOT 4: Total Attention Entropy (all layers and heads combined)
# =============================================================================

def plot_total_entropy(data: dict[str, np.ndarray]) -> None:
    """Single bar chart: entropy of total attention per token position,
    summed across all 16 layers × 32 heads and normalised."""
    has_total = all(f"{c}_total_entropy" in data for c in ["m1", "m2", "m3"])
    if not has_total:
        print("  Skipping total_entropy (no total data)")
        return

    m1_t = float(data["m1_total_entropy"][0])
    m2_t = float(data["m2_total_entropy"][0])
    m3_t = float(data["m3_total_entropy"][0])

    fig, ax = plt.subplots(figsize=(7, 5))
    bars = ax.bar(
        ["M1\n(full context)", "M2\n(NAMM, no LoRA)", "M3\n(LoRA + NAMM)"],
        [m1_t, m2_t, m3_t],
        color=[M1_COLOR, M2_COLOR, M3_COLOR],
        alpha=0.85, width=0.5,
    )
    for bar, val in zip(bars, [m1_t, m2_t, m3_t]):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.05,
                f"{val:.2f}", ha="center", va="bottom", fontsize=11)

    ax.set_ylabel("Entropy (nats)")
    ax.set_title("Total Attention Entropy\n"
                 "(attention summed across all layers and heads,\n"
                 "normalised per token position)",
                 fontsize=12, fontweight="bold")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    out = PLOT_DIR / "total_entropy.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"  Saved {out}")


# =============================================================================
# SUMMARY
# =============================================================================

def print_summary(data: dict[str, np.ndarray]) -> None:
    m1_ent = data["m1_entropy"]
    m3_ent = data["m3_entropy"]

    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"\nM1 (full ctx) entropy:  mean={m1_ent.mean():.4f}")
    if "m2_entropy" in data:
        m2_ent = data["m2_entropy"]
        print(f"M2 (evicted)  entropy:  mean={m2_ent.mean():.4f}")
    print(f"M3 (evicted)  entropy:  mean={m3_ent.mean():.4f}")

    diff = m3_ent - m1_ent
    pct = (m3_ent.mean() - m1_ent.mean()) / m1_ent.mean() * 100
    print(f"\nM3 vs M1: {pct:+.1f}%")
    print(f"Diff (M3 - M1): mean={diff.mean():.4f}, "
          f"min={diff.min():.4f}, max={diff.max():.4f}")

    if "m2_entropy" in data:
        m2_ent = data["m2_entropy"]
        m2_pct = (m2_ent.mean() - m1_ent.mean()) / m1_ent.mean() * 100
        m3_vs_m2 = (m3_ent.mean() - m2_ent.mean()) / m2_ent.mean() * 100
        print(f"M2 vs M1: {m2_pct:+.1f}%")
        print(f"M3 vs M2: {m3_vs_m2:+.1f}%")

    if "m3_retention" in data:
        ret = data["m3_retention"]
        print(f"\nM3 retention ratio: mean={ret.mean():.3f} "
              f"(range [{ret.min():.3f}, {ret.max():.3f}])")

    print("\n--- Per-Layer Mean Entropy ---")
    header = f"{'Layer':>5} | {'M1':>8}"
    if "m2_entropy" in data:
        header += f" | {'M2':>8}"
    header += f" | {'M3':>8} | {'M3-M1':>8}"
    print(header)
    print("-" * len(header))
    m1_layer = m1_ent.mean(axis=1)
    m3_layer = m3_ent.mean(axis=1)
    m2_layer = data["m2_entropy"].mean(axis=1) if "m2_entropy" in data else None
    for i in range(NUM_LAYERS):
        line = f"{i:5d} | {m1_layer[i]:8.4f}"
        if m2_layer is not None:
            line += f" | {m2_layer[i]:8.4f}"
        line += f" | {m3_layer[i]:8.4f} | {m3_layer[i] - m1_layer[i]:+8.4f}"
        print(line)


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    data = load_data()

    print("\nGenerating plots...")
    plot_attention_entropy(data)
    plot_entropy_heatmap(data)
    plot_entropy_diff(data)
    plot_total_entropy(data)

    print_summary(data)
    print("\nDone. All plots saved to:", PLOT_DIR)


if __name__ == "__main__":
    main()
