selection_criteria: ${topk_selection}

topk_selection:
  _target_: namm.policy.TopKSelection
  cache_size: ${cache_size}
  protected_tail_n: ${protected_tail_n}

protected_tail_n: 0

cache_size: 8192

selection_mp_log_name: topk-${cache_size}cs